version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: family_budget
    ports:
      - "5440:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

#volumes:
#  db-data:
