version: '3.9'

services:
  db:
    image: 'postgres:alpine'
    container_name: pg-server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: family_budget
    ports:
      - '2345:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

#volumes:
#  db-data:
