version: '3.9'

services:
  app:
    build: ./app
    image: 'bruslanb/app-family-budget-image:1.0.1'
    container_name: app-family-budget-container
    user: '1001:1001' # Specify the UID and GID of the user you want to run the container as
    depends_on:
      - db
    environment:
      - SERVER_PORT=8000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/family_budget
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8000
  db:
    image: 'postgres:alpine'
    container_name: db-pg-server-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: family_budget
    ports:
      - '5440:5432'
    volumes:
      - ./data:/var/lib/postgresql/data