# general settings
server:
  port: 8000

# spring settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/family_budget
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

# springdoc settings
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true

# actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"
      path-mapping:
        health: "healthcheck"
        info: "info"
        metrics: "metrics"
  endpoint:
    health:
      show-details: when_authorized

# logging setting
logging:
  root:
    level: ERROR
  file:
    name: logs/app.log
    append: true
  loggers:
    kz.bars.familybudget:
      level: INFO
  appenders:
    - type: file
      immediateFlush: true
      layout:
        type: pattern
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"