server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/family_budget
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
